### ISSUE TITLE
Přidat veřejné id pro boty v mapě

### ISSUE THREAD

**Issue by Contrix** [spseol/pybots-server#13]
Do objektu bot ("field" = 2) přidat paramert id, který by během jedné hry pro konkrétního bota zůstal stejný.
Aby bylo možné identifikovat pozici bota po n tazích.

**Comment by thejoeejoee** [comment]
Po vzájemné domluvě přibudou botům jména, v jejich objektu se bude nachátet klíč `name` s maximálně 10 znakovým jménem.
Můžu poprosit @tlapicka o nainstalování py balíčku `names`? díky.

**Comment by thejoeejoee** [comment]
Jest nainstalováno a mergnuto.

**Comment by MarrekNozka** [comment]
@thejoeejoee names je nainstalovaný.
