### ISSUE TITLE
Návratová hodnota POST

### ISSUE THREAD

**Issue by Contrix** [spseol/pybots-server#3]
Při POSTu vracet informaci o výsledku namísto výsledku.

**Comment by thejoeejoee** [comment]
Mám to promyšlené od refaktoringu chybových návratových hodnot do ReturnStates, přibudou tam i ty úspěšné.

**Comment by thejoeejoee** [comment]
Nyní by v každé odpovědi z /action měl být klíč `state`, jehož hodnota určuje stav provedení/neprovedení akce, @Contrix, vyhovuje Ti to takto?

**Comment by Contrix** [comment]
Naprosto vyhovuje. Děkuji.

**Comment by thejoeejoee** [comment]
Ještě poznamenám, možné stavy lze nalézt na `/info`, jedná se o dvojice textová hodnota a stavový HTTP kód odpovědi.
