### ISSUE TITLE
Informace uložené v mapě

### ISSUE THREAD

**Issue by Contrix** [spseol/pybots-server#4]
Do mapy bych ukládal pouze překážky → podklad, který se během hry nebude měnit. Ostatní informace (boti, poklad, atd.) do vlastních objektů.

**Comment by SonyPony** [comment]
Poklad se taky během hry nemění...

**Comment by Contrix** [comment]
Zatím ne, ale do budoucna bych nepočítal s tím, že se nebude hýbat.

**Comment by SonyPony** [comment]
Tím pádem jediné co bude statické během hry je pouze mapa, tudíž by se to muselo celé překopat, ale to nemá zas tak velký smysl, když Stejnak všichni si to nacpou do dvojrozměrného pole

**Comment by thejoeejoee** [comment]
Promýšlel jsem to a nejraději bych v onom poli polí posílal všechny informace z mapy, tzn. `0` pro prázdný blok a `{"type": "treasure"}`, příp. `{"type": "bot", "orientation": 0}` pro překážku, případně bota.

**Comment by Contrix** [comment]
I takové může být řešení. A ve výsledku to bude dokonce lepší.
Měním názor a volím tebou navrhovanou variantu.

**Comment by thejoeejoee** [comment]
Myslím, že aktuální struktura stavového JSONu je celkem vyhovující, nemám motivaci jej měnit, pro teď. Pokud přibudou nějaké další akční bloky, muselo by dojít k restrukturalizaci.
