### ISSUE TITLE
Rozehrané hry

### ISSUE THREAD

**Issue by Contrix** [spseol/pybots-server#6]
Po uplynutí určitého intervalu, od neaktivity všech zúčastněných botů na mapě, mapu odstranit.

**Comment by thejoeejoee** [comment]
To by šlo, nebudu potom muset přidávat i manuální mazání her, které by bylo lehce problematické vzhledem k aktivním botů ve hře.

**Comment by thejoeejoee** [comment]
Akutálně lze v administraci po určité době neaktivity ve hře (1 minuta aktuálně) hru smazat.

**Comment by thejoeejoee** [comment]
Nyní jde v administraci smazat i všechny hry hromadně, které jsou neaktivní po více jak 30 sekund.
